previewsEnabled: true

services:
  - type: web
    name: poc
    env: docker
    dockerCommand: ./entrypoint.sh
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: pocredis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: pocredis
          property: port
      - key: DB_URL
        fromDatabase:
          name: pocdb
          property: connectionString
  - type: worker
    name: queue
    dockerCommand: ./worker.sh
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: pocredis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: pocredis
          property: port
      - key: DB_URL
        fromDatabase:
          name: pocdb
          property: connectionString
  - type: redis
    name: pocredis
    ipAllowList:
      - source: 0.0.0.0
        description: everywhere


databases:
  - name: pocdb
