previewsEnabled: true

services:
  - type: web
    name: poc
    env: docker
    dockerCommand: python manage.py runserver 0.0.0.0:8000
    pullRequestPreviewsEnabled: true
    envVars:
      - key: DB_URL
        fromDatabase:
          name: pocdb
          property: connectionString
      - key: TEST
        value: 999

databases:
  - name: pocdb
