previewsEnabled: true

services:
  - type: web
    name: poc
    env: docker
    # dockerCommand: python manage.py runserver 0.0.0.0:8000
    dockerCommand: ./entrypoint.sh
    pullRequestPreviewsEnabled: true
    envVars:
      - key: DB_URL
        fromDatabase:
          name: pocdb
          property: connectionString
      - key: TEST
        value: 999
  - type: redis
    name: pocredis
    ipAllowList:
      - source: 0.0.0.0
        description: everywhere


databases:
  - name: pocdb
